const ADD_TODO = "ADD_TODO"

const ADD_TODO_TO_STORE = 'ADD_TODO_TO_STORE'

const DELETE_TODO = 'DELETE_TODO'

const EDIT_TODO = 'EDIT_TODO'

export {ADD_TODO, ADD_TODO_TO_STORE, DELETE_TODO, EDIT_TODO}